### ISSUE TITLE
Disable all sections but mode

### ISSUE THREAD

**Issue by sebiwi** [michaelbrusegard/tabline.wez#25]
Hello,

I'm trying to only enable the mode section of the bar, but all the other sections (available disk, etc) keep appearing.

This is my config:

```
sections = { tabline_a = { 'mode' } }
```

Is this normal, or a bug?

Thanks!

**Comment by michaelbrusegard** [comment]
This is as expected. You need to overwrite the other sections with empty tables. If you don't it will use the default config. tabline_a is set to mode by default so you actually do not need to set it. See example below:
```lua
sections = {
  tabline_b = {},
  tabline_c = {},
  tab_active = {},
  tab_inactive = {},
  tabline_x = {},
  tabline_y = {},
  tabline_z = {},
}
```
