### ISSUE TITLE
Can't override icon for `workspace`.

### ISSUE THREAD

**Issue by tj-smith47** [michaelbrusegard/tabline.wez#27]
Have tried both of the 2 approaches below, neither set the icon. Perhaps not a bug, but rather a documentation gap. Either way, any help for how to set this is much appreciated:
```lua
tabline_b = {
	"workspace",
	icon = { "default", wezterm.nerdfonts.dev_apple, color = { fg = scheme.ansi[3] } },
},

-- and

tabline_b = {
	"workspace",
	icon = { wezterm.nerdfonts.dev_apple, color = { fg = scheme.ansi[3] } },
},
```
where `local scheme = wezterm.color.get_builtin_schemes()["Dracula (Official)"]`. Can you see what I might be doing wrong?

**Comment by michaelbrusegard** [comment]
Seems to be a bug. I will try to fix it

**Comment by michaelbrusegard** [comment]
@tj-smith47 Nevermind, there is no bug. You are missing the brackets around the workspace object so the icon is never applied to anything. This is how it should look:
```lua
      tabline_b = {
        {
          'workspace',
          icon = { wezterm.nerdfonts.dev_apple, color = { fg = colors.ansi[3] } },
        },
      },
```

**Comment by michaelbrusegard** [comment]
I spent way to much time trying to debug this only to there not being anything wrong with the code. Well hopefully you got everything working now.

**Comment by tj-smith47** [comment]
@michaelbrusegard sorry about that. I appreciate your time, it did resolve my issue.

**Comment by michaelbrusegard** [comment]
Nice! I am happy you got it working :). I got a good refresher on some of the code now
