### ISSUE TITLE
Feature Request: Support for Customizing Active and Inactive Process Icon Colors

### ISSUE THREAD

**Issue by 0xJWLabs** [michaelbrusegard/tabline.wez#39]
Currently, the process_to_icon functionality allows setting an icon color, but the same color is applied to both active and inactive states. This limits customization and visual distinction between different states of a process. Adding the ability to customize the icon color separately for active and inactive states would provide more flexibility and enhance the UI's clarity and responsiveness.

# Proposal
Maybe a config like this?
```lua
process_to_icon = {
  ['apt'] = { wezterm.nerdfonts.dev_debian, active_color = { fg = scheme.ansi[2] }, inactive_color = { fg = scheme.ansi[1] }
}
```

**Comment by michaelbrusegard** [comment]
Since `process` is using the same color function as every other component, it would be a larger rewrite to support this. I will accept a good PR if everything is implemented correctly, but it will lead to breaking changes for others. I think it would actually be better to have its own plugin for a component like this than can be added to `tabline.wez` similar to the `battery.wez` plugin component.

**Comment by 0xJWLabs** [comment]
Uhm maybe something like lualine might be good? it has like extend from base component?

**Comment by 0xJWLabs** [comment]
Btw this is kind of out of topic, does wezterm use somehow like encoder for the plugin path? if i wanna refer it to local directory how to get the encoded path?

**Comment by 0xJWLabs** [comment]
Or maybe something like this?

```lua
{
  function()
    return " "
  end,
  padding = { left = 0, right = 1 }
}
```

**Comment by michaelbrusegard** [comment]
I am not completely sure what you are asking. If you want to create your own component you can just create function that returns a string and put that function in the section you want

**Comment by michaelbrusegard** [comment]
You can just add spaces on each side of the string, it is the same thing

**Comment by 0xJWLabs** [comment]
hey, sorry it’s unrelated but i wanna talk about your dotfiles, where can we talk?

**Comment by michaelbrusegard** [comment]
You can send me an Email and I will answer when I have time, you can find it on my GitHub profile

**Comment by michaelbrusegard** [comment]
I am gonna close this as it seems inactive and it is out of the scope of this plugin and could instead be its own component
