### ISSUE TITLE
Discrepancy between right Nerdfont tab seperator bg color on inactive tabs 

### ISSUE THREAD

**Issue by slh-git** [michaelbrusegard/tabline.wez#40]
See right most inactive tab: 

![Screenshot from 2024-10-18 18-08-38](https://github.com/user-attachments/assets/993c6608-361f-41b9-a8d6-2d40d0a3f28c)

config: 

```
local tabline = wezterm.plugin.require("https://github.com/michaelbrusegard/tabline.wez")

tabline.setup({})

tabline.apply_to_config(config)
```

**Comment by michaelbrusegard** [comment]
<img width="1662" alt="Screenshot 2024-10-19 at 05 32 03" src="https://github.com/user-attachments/assets/be339836-fe42-4536-9113-54b84b7a7de9">
The issue does not happen for me with the default config. Are you sure you are using the latest version of the plugin? I am unable to reproduce it

**Comment by slh-git** [comment]
Is there for me to confirm the plugin version?

**Comment by michaelbrusegard** [comment]
You can use `wezterm.plugin.update_all()` to update all plugins or you can delete the plugin folder manually and it will reinstall when you reload your config

**Comment by slh-git** [comment]
Unfortunately the issue still persists after i put the command in and reload the config & wezterm

**Comment by michaelbrusegard** [comment]
It is very difficult to debug when I am unable to recreate it, are there any other steps you may have taken that may differ? Or maybe it is a windows issue if you are using that?

**Comment by slh-git** [comment]
The machine that I opened the issue on is running Fedora 40 (wezterm nightly). Interestingly, after reading your message, I also tried installing on the wezterm on my windows machine out of curiosity and found similar results.

![image](https://github.com/user-attachments/assets/a5732506-8403-458f-a2f2-bec6e4667995)

![image](https://github.com/user-attachments/assets/e456f1dd-3fbf-47b5-af03-71551a053951)

**Comment by khaled4vokalz** [comment]
while investigating this a bit I found out that there's something conflicting with the wezterm theme. E.g. If I use the default wezterm theme I see this.

![image](https://github.com/user-attachments/assets/472008b7-4305-4cfe-a2da-4103ebf3326a)

It seems like the default wezterm theme and the tabline themes are not completely same. e.g. for `color_scheme = "Catppuccin Macchiato"` in **wezterm.lua** and `theme = "Catppuccin Macchiato"` in `tabline#setup` I see below output. 

![image](https://github.com/user-attachments/assets/c9a97648-b5c2-4265-9f3a-e79c4b7f7906)

**Comment by michaelbrusegard** [comment]
@khaled4vokalz You could clone the repository and use the local version then change the separator attributes in the `tabs.lua` fie and see if you are able to resolve it. But everything seems to be correct when I look at it. It should always use the `inactive.bg` color for the separator background no matter what. Can you use a color picker on the wrongfully showed color so we can see where it comes from? Everything should be setup correctly with the default config so maybe try to see if the issue persists there
