### ISSUE TITLE
Tabline should not set window_decorations options

### ISSUE THREAD

**Issue by ekorchmar** [michaelbrusegard/tabline.wez#42]
https://github.com/michaelbrusegard/tabline.wez/blob/7ca0479c06284db77ab826805063f3c71a8b20e2/plugin/init.lua#L52C9-L52C11

Title. Plugins should not silently manage and override unrelated user configuration.

**Comment by michaelbrusegard** [comment]
While I agree with what you are saying, as outlined in the documentation, calling the apply_to_config method is completely optional. The settings set there is for a quicksetup if you dont want it you can set the options you want manually which is what I am doing in my config

**Comment by michaelbrusegard** [comment]
I will close this because of no response
