### ISSUE TITLE
Show if leader key is active

### ISSUE THREAD

**Issue by victor-falcon** [michaelbrusegard/tabline.wez#43]
I was using something similar to this to show in the right status if the lead key is active or not.

```
local wezterm = require 'wezterm'

wezterm.on('update-right-status', function(window, pane)
  local leader = ''
  if window:leader_is_active() then
    leader = 'LEADER'
  end
  window:set_right_status(leader)
end)

return {
  leader = { key = 'a', mods = 'CTRL' },
  colors = {
    compose_cursor = 'orange',
  },
}
```

It's possible to something similar with tabline?

**Comment by victor-falcon** [comment]
Ok, I just do this and it seems it's working

```
{
  "workspace",
  icons_enabled = false,
  fmt = function(workspace, window)
    if window:leader_is_active() then
      return workspace .. " " .. "🟡"
    end
  
    return workspace .. " " .. "⚪"
  end,
},
```

**Comment by michaelbrusegard** [comment]
If you want I can add this as its own extension as it is a pretty simple addition

**Comment by victor-falcon** [comment]
I think it would be very useful.

I have just changed my config and replaced the mode component with an icon. I would also like to change the colors, just to make it more noticeable, but right now I'm happy with this current config.

```
	{
		"mode",
		padding = { left = 1, right = 2 },
		fmt = function(mode, window)
			if window:leader_is_active() then
				return wezterm.nerdfonts.md_keyboard_outline
			elseif mode == "NORMAL" then
				return wezterm.nerdfonts.cod_terminal
			elseif mode == "COPY" then
				return wezterm.nerdfonts.md_scissors_cutting
			elseif mode == "SEARCH" then
				return wezterm.nerdfonts.oct_search
			end

			return mode
		end,
	},
```

**Comment by michaelbrusegard** [comment]
> I think it would be very useful.
> 
> I have just changed my config and replaced the mode component with an icon. I would also like to change the colors, just to make it more noticeable, but right now I'm happy with this current config.
> 
> ```
> 	{
> 		"mode",
> 		padding = { left = 1, right = 2 },
> 		fmt = function(mode, window)
> 			if window:leader_is_active() then
> 				return wezterm.nerdfonts.md_keyboard_outline
> 			elseif mode == "NORMAL" then
> 				return wezterm.nerdfonts.cod_terminal
> 			elseif mode == "COPY" then
> 				return wezterm.nerdfonts.md_scissors_cutting
> 			elseif mode == "SEARCH" then
> 				return wezterm.nerdfonts.oct_search
> 			end
> 
> 			return mode
> 		end,
> 	},
> ```

I can add the component, please make a feature request with details on everything you want in this component and I will have a look when I find the time :)
