### ISSUE TITLE
Can't rename tabs

### ISSUE THREAD

**Issue by thomascrha** [michaelbrusegard/tabline.wez#47]
Hi there - I have configured this key binding

```lua
  {
    key = ',',
    mods = 'LEADER',
    action = act.PromptInputLine {
      description = 'Enter new name for tab',
      -- initial_value = 'My Tab Name',
      action = wezterm.action_callback(function(window, pane, line)
        -- line will be `nil` if they hit escape without entering anything
        -- An empty string if they just hit enter
        -- Or the actual line of text they wrote
        if line then
          window:active_tab():set_title(line)
        end
      end),
    },
  },
```
Taken from the official docs here [example-of-interactively-renaming-the-current-tab](https://wezfurlong.org/wezterm/config/lua/keyassignment/PromptInputLine.html#example-of-interactively-renaming-the-current-tab)

But when i rename the tab tabline doesn't adhere to the rename. If i disable the plugin (or even use something like [bar.wezterm](https://github.com/adriankarlen/bar.wezterm) it works as expected.

Also this is my current config - pretty much stock
```lua
local tabline = wezterm.plugin.require("https://github.com/michaelbrusegard/tabline.wez")
tabline.setup({
  options = { theme = 'OneHalfDark' }
})
tabline.apply_to_config(config)
```

I'm thinking this can be changed somehow in the configuration - but I couldn't figure it out - I'm probably just missing it/dumb.

**Comment by michaelbrusegard** [comment]
hmm, this plugin does overwrite the name so that makes sense. You could probably pass a variable to be displayed in the tabline and then change that variable in the keybind action? But I am not sure to be honest

**Comment by thomascrha** [comment]
Would it be possible to expose a config var for the tabs section that doesn't rename the tab ? It seems kinda difficult - you have alot of custom logic and features around detecting whats happening inside the tab and exposing it by then renaming the tab - it might be that this isn't the plugin for me - as i actually get the feature - i just don't want it. I'll take a look and see what i can make of it - but lua experience is pretty minimal.

**Comment by erlestor** [comment]
I would love this. I also want to turn off tabs showing the cwd when active. I like my tabs to stay the same length all the time

**Comment by michaelbrusegard** [comment]
> Would it be possible to expose a config var for the tabs section that doesn't rename the tab ? It seems kinda difficult - you have alot of custom logic and features around detecting whats happening inside the tab and exposing it by then renaming the tab - it might be that this isn't the plugin for me - as i actually get the feature - i just don't want it. I'll take a look and see what i can make of it - but lua experience is pretty minimal.

Do you want a config option to disable the tab customization functionality specifically? That is very doable and I can add that  if I understand you correctly

**Comment by thomascrha** [comment]
Thank You !
