### ISSUE TITLE
tabline keeps causing wezterm to crash becasue of set_status

### ISSUE THREAD

**Issue by Alan-Manning** [michaelbrusegard/tabline.wez#50]
i have been experiencing crashes with wezterm as of a few weeks ago. perhaps the latest commit. this is the error i recieve from weterm logs:
`19:03:00.627  ERROR  wezterm_gui::termwindow > while processing update-status event: bad argument #1: error converting Lua table to termwiz_funcs::FormatItem (error converting Lua function to wezterm_dynamic::Value)
stack traceback:
	[C]: in function 'wezterm.format'
	...elbrusegardsZstablinesDswez\plugin\tabline\component.lua:171: in function 'tabline.component.set_status'
	...DscomsZsmichaelbrusegardsZstablinesDswez/plugin/init.lua:38: in function <...DscomsZsmichaelbrusegardsZstablinesDswez/plugin/init.lua:37>
`

i havent dug into this really as i am busy with other bits but thought it was worth making this issue to track.

**Comment by michaelbrusegard** [comment]
Hmm, I am not sure. Have you experienced any unexpected behaviour when using it? Or are there any specific actions you  are doing that is causing the crash?

**Comment by Alan-Manning** [comment]
> Hmm, I am not sure. Have you experienced any unexpected behaviour when using it? Or are there any specific actions you are doing that is causing the crash?

i cant recall specifics but its using in nvim. the term goes super laggy, then maybe it might fix itself but more than likely it just crashes. the only thing i do recall is i have the tab name to be the dir name but sometimes is just doesnt pick up the correct working dir and sets to something random that nvim was using like the dist folder somewhere.

**Comment by michaelbrusegard** [comment]
Weird, I am using it with Neovim without issues every day. Maybe something in your environment is causing the issue? Are you using the default config for the plugin? And have you isolated the issue to be only when the plugin is used?

**Comment by Alan-Manning** [comment]
> Weird, I am using it with Neovim without issues every day. Maybe something in your environment is causing the issue? Are you using the default config for the plugin? And have you isolated the issue to be only when the plugin is used?

I will put my config on git some point tomorrow. i have done some extra stuff to get git repo and stuff. ill look into a bit more when i make the repo.

**Comment by michaelbrusegard** [comment]
Did you figure out the issue?

**Comment by michaelbrusegard** [comment]
I will close this as stale for now, but feel free to reopen
