### ISSUE TITLE
Feature Request: another icon for datetime

### ISSUE THREAD

**Issue by aniketgm** [michaelbrusegard/tabline.wez#57]
## Request

For the `sections`>>`tabline_a`>>`datetime` setup, can we have an `icon` variable that overrides the default `hour_to_icon` ? What do you think ?

### Explanation

In the setup, in addition to the `hour_to_icon` config, can we have another icon config, (name of variable can be anything, for e.g. `other_icon`). When I specify the date (not time). I would like to have some date/calender icon and not the default `hour_to_icon`
```lua
sections = {
  tabline_a = {
    {
      ....
      style = "%Y/%m/%d",
      -- hour_to_icon = {
      --   ['00'] = wezterm.nerdfonts.md_clock_time_twelve_outline,
      --   ....
      --   ['23'] = wezterm.nerdfonts.md_clock_time_eleven,
      -- },
      other_icon = wezterm.nerdfonts.md_calendar -- Just an example. it can be any icon here that one likes.
    },
  },
}
```

So, I have this config:
```lua
tabline.setup({
  ....
  sections = {
    ....
    tabline_x = { { "datetime", style = "[%a] %b/%d" } }, -- here I would like another icon since the style is not hours/minutes.
  },
})
```

**Comment by michaelbrusegard** [comment]
you can already do that, by giving the component a custom icon and setting hour_to_icon to nil.
```lua
sections = {
  tabline_a = {
    {
      'datetime',
      hour_to_icon=nil,
      icon=wezterm.nerdfonts.md_calendar,
    },
  },
}
```

this should probably work

**Comment by aniketgm** [comment]
> you can already do that, by giving the component a custom icon and setting hour_to_icon to nil.

Nope, doesn't work. I tried the following:
```lua
sections = {
  ....
  tabline_x = {
    {
      "datetime",
      style = "[%a] %b/%d",
      hour_to_icon = nil,
      icon = wz.nerdfonts.md_calendar,
    },
  },
},
```

**Comment by michaelbrusegard** [comment]
Glad you got it working. Probably have to add a nil check, thought that would be the equivalent to false :)
